# Limpieza

## Importación de librerías

In [1]:
import pandas as pd

In [4]:
# Configuramos que se muestren todas las columnas de nuestros dataframes
pd.set_option('display.max_columns', None)

## Carga de Datos

In [5]:
df_bank = pd.read_csv('files/output/df_bank_ap.csv')

In [6]:
df_bank.sample(2)

,AGE,JOB,MARITAL,EDUCATION,DEFAULT,HOUSING,LOAN,CONTACT,DURATION,CAMPAIGN,PDAYS,PREVIOUS,POUTCOME,EMPVARRATE,CONSPRICEIDX,CONSCONFIDX,EURIBOR3M,NREMPLOYED,Y,DATE,ID
18238,44.0,admin.,divorced,high-school,no,yes,yes,cellular,75,11,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,no,2018-07-25,9bded965-e3f3-4a11-888c-b234a4c46c7d
11007,NaN,self-employed,married,high-school,no,no,no,telephone,340,1,999,0,nonexistent,1.4,94.465,-41.8,4.961,5228.1,no,2019-09-24,86bf606d-3928-45a8-84bd-7ee377d66767

In [10]:
df_customer = pd.read_csv('files/output/df_customer_ap.csv')

In [11]:
df_customer.sample(2)

,INCOME,KIDHOME,TEENHOME,DTCUSTOMER,NUMWEBVISITSMONTH,ID
34036,80313,1,0,2014-10-13,1,b00f72a4-c87f-4f7c-94d4-7384dcc94dcc
34508,79087,1,1,2014-10-26,7,bd5a1854-964f-4b81-8c35-db4de59ea054